# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

stages:          # List of stages for jobs, and their order of execution
  - build

variables:
  GOPROXY: https://goproxy.cn,direct

image: golang:1.17
#image: busybox

compose-build:
  stage: build
  artifacts:
    expire_in: 1 day
    paths:
      - murphysec-linux-amd64
      - murphysec-windows-amd64.exe
      - murphysec-darwin-amd64
      - murphysec-linux-amd64.sha256
      - murphysec-windows-amd64.exe.sha256
      - murphysec-darwin-amd64.sha256
  script:
    - export
    - GOOS=linux GOARCH=amd64 go build -o out/murphysec-linux-amd64 -v .
    - GOOS=windows GOARCH=amd64 go build -o out/murphysec-windows-amd64.exe -v .
    - GOOS=darwin GOARCH=amd64 go build -o out/murphysec-darwin-amd64 -v .
    - cd out
    - chmod 0755 *
    - find -type f | xargs -I {} sh -c "sha256sum {} > {}.sha256"
    - cat *.sha256
    - sha256sum -c *.sha256
    - mv * ../
    - cd ..
  
