stages: # List of stages for jobs, and their order of execution
  - build
  - internal-pub
  - notify

variables:
  GOPROXY: https://goproxy.cn,direct
  GOPATH: "$CI_PROJECT_DIR/.go"
  GOBIN: "$CI_PROJECT_DIR/.go/bin"
  CGO_ENABLED: '0'
  DENO_DIR: "$CI_PROJECT_DIR/.deno"
  GOCACHE: "$CI_PROJECT_DIR/.go-cache"

compose-build:
  image: golang:1.19.2-bullseye
  stage: build
  artifacts:
    expire_in: 1 day
    paths:
      - out/bin/*
  cache:
    key: cli-build-cache-v3
    paths:
      - .go/pkg/mod/
      - .go-cache/
  before_script:
    - mkdir -p .go-cache
    - mkdir -p .go
  rules:
    - if: '$CI_COMMIT_TAG == null'
  script:
    - GOOS=windows GOARCH=amd64 go build -v -ldflags "-s -w -buildid=" -trimpath -o out/bin/murphysec-windows-amd64.exe .
    - GOOS=linux GOARCH=amd64 go build -v -ldflags "-s -w -buildid=" -trimpath -o out/bin/murphysec-linux-amd64 .
    - GOOS=linux GOARCH=arm64 go build -v -ldflags "-s -w -buildid=" -trimpath -o out/bin/murphysec-linux-arm64 .
    - GOOS=darwin GOARCH=amd64 go build -v -ldflags "-s -w -buildid=" -trimpath -o out/bin/murphysec-darwin-amd64 .
    - GOOS=darwin GOARCH=arm64 go build -v -ldflags "-s -w -buildid=" -trimpath -o out/bin/murphysec-darwin-arm64 .

compose-build-with-tag:
  image: golang:1.19.2-bullseye
  stage: build
  artifacts:
    expire_in: 1 day
    paths:
      - out/bin/*
  cache:
    key: cli-build-cache-v3
    paths:
      - .go/pkg/mod/
      - .go-cache/
  before_script:
    - mkdir -p .go-cache
    - mkdir -p .go
  rules:
    - if: '$CI_COMMIT_TAG != null'
  script:
    - GOOS=windows GOARCH=amd64 go build -v -ldflags "-s -w -X github.com/murphysecurity/murphysec/infra/buildinfo.version=$CI_COMMIT_TAG -buildid=" -trimpath -o out/bin/murphysec-windows-amd64.exe .
    - GOOS=linux GOARCH=amd64 go build -v -ldflags "-s -w -X github.com/murphysecurity/murphysec/infra/buildinfo.version=$CI_COMMIT_TAG -buildid=" -trimpath -o out/bin/murphysec-linux-amd64 .
    - GOOS=linux GOARCH=arm64 go build -v -ldflags "-s -w -X github.com/murphysecurity/murphysec/infra/buildinfo.version=$CI_COMMIT_TAG -buildid=" -trimpath -o out/bin/murphysec-linux-arm64 .
    - GOOS=darwin GOARCH=amd64 go build -v -ldflags "-s -w -X github.com/murphysecurity/murphysec/infra/buildinfo.version=$CI_COMMIT_TAG -buildid=" -trimpath -o out/bin/murphysec-darwin-amd64 .
    - GOOS=darwin GOARCH=arm64 go build -v -ldflags "-s -w -X github.com/murphysecurity/murphysec/infra/buildinfo.version=$CI_COMMIT_TAG -buildid=" -trimpath -o out/bin/murphysec-darwin-arm64 .

internal-cos-upload:
  image: iseki0/cos-uploader:v1.1.3
  stage: internal-pub
  artifacts:
    expire_in: 1 day
    paths:
      - out/zip/*
  script:
    - mkdir out/zip
    - bash -c "cd out/bin/ && zip ../zip/pro.zip *"
    - cos-uploader --local out/bin/murphysec-windows-amd64.exe --remote /client/$CI_BUILD_REF_NAME/murphysec-windows-amd64.exe
    - cos-uploader --local out/bin/murphysec-linux-amd64 --remote /client/$CI_BUILD_REF_NAME/murphysec-linux-amd64
    - cos-uploader --local out/bin/murphysec-linux-arm64 --remote /client/$CI_BUILD_REF_NAME/murphysec-linux-arm64
    - cos-uploader --local out/bin/murphysec-darwin-amd64 --remote /client/$CI_BUILD_REF_NAME/murphysec-darwin-amd64
    - cos-uploader --local out/bin/murphysec-darwin-arm64 --remote /client/$CI_BUILD_REF_NAME/murphysec-darwin-arm64
    - cos-uploader --local out/zip/pro.zip --remote /client/$CI_BUILD_REF_NAME/pro.zip
    - cos-uploader --local out/bin/murphysec-windows-amd64.exe --remote /client/-/murphysec-windows-amd64.exe
    - cos-uploader --local out/bin/murphysec-linux-amd64 --remote /client/-/murphysec-linux-amd64
    - cos-uploader --local out/bin/murphysec-linux-arm64 --remote /client/-/murphysec-linux-arm64
    - cos-uploader --local out/bin/murphysec-darwin-amd64 --remote /client/-/murphysec-darwin-amd64
    - cos-uploader --local out/bin/murphysec-darwin-arm64 --remote /client/-/murphysec-darwin-arm64
    - cos-uploader --local out/zip/pro.zip --remote /client/-/pro.zip

lark-notify:
  image: denoland/deno
  stage: notify
  cache:
    key: cli-deno-cache-1223
    paths:
      - .deno
  script:
    - deno run --allow-all ci/lark-push.ts

